FROM node:20-alpine

WORKDIR /app

# Copy Packages (needed for typescript alias resolution)
# Structure in docker:
# /app/packages/shared
# /app/apps/web

COPY packages ./packages
COPY apps/web ./apps/web

WORKDIR /app/apps/web

# Install dependencies
RUN npm install

# Build
RUN npm run build

# Expose
EXPOSE 5173

# Run preview
# Host 0.0.0.0 is needed for docker
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]
